<a href="https://colab.research.google.com/github/JF11579/Plotly_RE/blob/main/RockyPoint_import.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notes

# Library

In [ ]:
# !pip install geopandas
# !pip install geopy

In [ ]:
 #from geopy.geocoders import Nominatim

# # Create a Nominatim geocoder object with a user agent
# geolocator = Nominatim(user_agent="myGeocoder")

# # # geolocator = geocoders.Nominatim(user_agent="my_app")
# #
# from geopy.geocoders import Nominatim


# # Create a GeoPy geocoder
# geolocator = Nominatim(user_agent="my_app")

In [ ]:
import pandas as pd
from google.colab import drive
import plotly.express as px
import numpy as np

# Options

In [ ]:
# Set pandas display options to show more rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Data

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Change to the directory containing your CSV
%cd /content/drive/MyDrive/DATA/Real_Estate_Data

Mounted at /content/drive
/content/drive/MyDrive/DATA/Real_Estate_Data

In [ ]:
condo = pd.read_csv('RockyWheatCalHolt.csv')

In [ ]:
condo.head(1)

,Air Conditioning,Acres,Property Description,Address,Agency,Also For Rent,Interior Features,Apt#,Attic Description,Auxiliary Rooms,Baths Full,Baths Half,Buyer Agency Compensation,Waterfront Features,Building,Building Permit,Block,Listing Broker Phone #,Bedrooms,Branch,Modifications Exclusions,Basement Description,Room Level,Bath,Business Age,Business Type,Utilities Included,Included,Cash Down,Contract Cancel Effective Date,Contract Date,Under Steel,Available Utilities,Class Description,Co-Listing Agent,Co-Listing Agent2,Broker Code,Common Charges,Commission Oblig Date,Compensation Paid By,Compass Points,Appearance,W/R Conditions,Construction Description,Lot Description,County,Contract Price,Cross Street,Location Features,DBA,Exterior Features,Deductible %,Income Desc 1,Income Desc 2,Income Desc 3,Income Desc 4,Income Desc 5,Income Desc 6,Income Desc 7,Income Desc 8,Detached/Attached,Development,District,Days On Market,Driveway,Fees,Finance Restrictions,Final Mortgage,Fixtures & Equipment,Floor Load,REO,# Fireplaces,Frontage Feet,Feet From Corner,Heating Fuel,Parking,LandLord Pays,Gross Profit %,Building Features,Heating Type,Hilp$,Inc 1 $,Inc 2 $,Inc 3 $,Inc 4 $,Inc 5 $,Inc 6 $,Inc 7 $,Inc 8 $,Inventory Included,Insurance,Distribute To Internet Portals,Inventory,Listing Date,Lease,Topography,Listing Agent,Number of Docks,Lockbox,Lolp$,Lot,Lot Square Footage,Lot Size,Listing Price,Last Status Change,Lease Years,Last Update Date,Maintenance,Maintenance/Repairs Expense,Minimum Plot Size,Miscellaneous Expense,ML#,Model Name,Moved From,Mortgage Type,Negotiate Direct,Net Income,New Construction,# Families,# Floors In Building,# Floors In Unit,# Kitchens,# Plots,# Units,# Heating Zones,Occupancy,Office %,Broker Open House Description,Broker Open Houses,Lease Conditions,Original Price,Other Fees,Out of Area Town,Owner,Owner Financing,Parking Charges,Parking Facilities,Parking Spaces,Parking Spaces At Building,Payroll Expense,% Difference,Permit,Personal Property Exclusion,Pets Allowed,Status/Showing Phone,Planning Board Approved,Pool Description,Possible Subdivision,Price Range Listing,Property Type,Proposed Title Date,Purchaser,Renting Broker Branch,Renting Broker Code,Renting Broker Compensation,Rented Date,Road Surface,Remarks,Rent Expense,Renting Agent,Rent Income,Rent Per Square Foot,Rental Type,Relist Obligation Date,Listing Broker,Rooms,Rented Price,Renting Broker,Sale or Rent,Selling Broker Branch,Selling Broker Code,Seller Agency Compensation,School District Name,School District #,Seats,Section,Section/Area,Security Deposit,Selling Agent,Separate Hotwater Heater,Show Instructions,Sold Price,Approx Int Square Footage,Selling Broker,Street Name,Street Direction,Street Number,Street Suffix,Status,State,Stories,Style,Supercedes ML#,Taxes,Taxes W/Star Exemption,Title Date,TOM,Terms,TOM Start Date,TOM End Date,Total Expenses,Total Income,Town,Type Ownership,Type Sale,Unit #,Unit on Floor #,Vacancy %,Development Status,Village Taxes,Water Frontage,Water Description,Wooded/Cleared,Withdrawn/Release Date,Exp Date,Year Built,Zip,Zone,Zoning,Unnamed: 219
0,Central,NaN,Fully updated corner unit of the Waverly Park ...,219 Storm Drive,Excl Agency,N,"Eat in Kitchen,Hardwood Floors As Seen,Walk In...",NaN,None,NaN,1,0,2%,NaN,NaN,NaN,3.0,516-717-9079,2,1,None,None,"1,2",1.0,NaN,NaN,NaN,NaN,NaN,NaN,7/21/2023,NaN,NaN,Condo,NaN,NaN,ALAE,310.0,NaN,NaN,NaN,NaN,NaN,Frame,NaN,S,NaN,Storm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Det,Waverly Park,500,8.0,NaN,NaN,NaN,NaN,NaN,NaN,N,0.0,NaN,NaN,Natural Gas,Lot Parking,NaN,NaN,NaN,Forced Air,356750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7/13/2023,NaN,NaN,Erick K Alahverdian,NaN,N,356750,300.0,3485.0,NaN,356750,PEN,NaN,7/21/2023,NaN,NaN,NaN,NaN,3490982,Model F Home,NaN,NaN,N,NaN,N,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,356750,NaN,NaN,Oneill,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"All Dogs,Cats",516-717-9079,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sale may be subject to term & conditions of an...,NaN,NaN,NaN,NaN,NaN,NaN,Grace Rose Realty LLC,5,NaN,NaN,NaN,1.0,ALAE,0,Sachem,NaN,NaN,91.0,NaN,NaN,Haig K Baghdassarian,NaN,Use Showingtime App to schedule,NaN,NaN,Grace Rose Realty LLC,Storm,NaN,219,Drive,U,NY,NaN,Other,NaN,3534.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Holtsville,Condo,NaN,219,1.0,NaN,NaN,NaN,NaN,Other/See Remarks,NaN,NaN,2/13/2024,1972,11742,28,NaN,NaN

In [ ]:
condo.rename(columns=lambda x: x.replace(' ', '_'), inplace=True)
condo = condo.drop_duplicates(subset=['ML#'], keep='first')
condo.dropna(subset=['Sold_Price'], inplace=True)

In [ ]:
condo = condo[['ML#', 'Style','Development','Sold_Price','Baths_Full', 'Baths_Half',
                   'Bath','Bedrooms','REO','Appearance','Approx_Int_Square_Footage',
                'Unit_on_Floor_#','Contract_Date','Days_On_Market','Listing_Date','Title_Date']]

In [ ]:
condo.head(1)

,ML#,Style,Development,Sold_Price,Baths_Full,Baths_Half,Bath,Bedrooms,REO,Appearance,Approx_Int_Square_Footage,Unit_on_Floor_#,Contract_Date,Days_On_Market,Listing_Date,Title_Date
1,3289207,Other,Rocky Point Owners,76000,1,0,1.0,1,N,Excellent,NaN,2.0,4/07/2021,44.0,2/21/2021,7/16/2021

In [ ]:
condo['Baths_Full'].fillna(1, inplace=True)
# Then, convert the column to integers
condo['Baths_Full'] = condo['Baths_Full'].astype(int)
# I ti spossible tha the unit not have any
#half baths but only full units

condo['Baths_Half'].fillna(0, inplace=True)

# Then, convert the column to integers
condo['Baths_Half'] = condo['Baths_Half'].astype(int)
condo['Bath'].fillna(1, inplace=True)

# Then, convert the column to integers
condo['Bath'] = condo['Bath'].astype(int)

In [ ]:
# change the text description of the condo to a ordinal number:
appearance_data = condo

def map_existing_values(value):
    if pd.isna(value):  # Handle NaN values explicitly
        return 0
    if value == "Appearance":
        return 0
    elif value in ["AS IS"]:
        return 1
    elif value in ["Fair", "good", "Good", "Very Good", "Very good"]:
        return 2
    elif value in ["Excellent", "EXCELLENT"]:
        return 3
    elif value == "Move in":
        return 3
    elif value in ["diamond", "Diamond", "Mint", "mint", "Mint+", "Mint++", "Mint+++", "Mint+++"]:
        return 4
    elif value == "unknown":
        return 0

condo['Appearance_Ordinal'] = condo['Appearance'].apply(map_existing_values)

In [ ]:
condo['Appearance_Ordinal'].fillna(0, inplace=True)

condo['REO_Ordinal'] = condo['REO'].apply(lambda x: 1 if x == 'Y' else 0)

# prompt: convert Bedrooms to integers

condo['Bedrooms'].fillna(1, inplace=True)

# Then, convert the column to integers
condo['Bedrooms'] = condo['Bedrooms'].astype(int)

# Convert 'Bedrooms' to a categorical data type
condo['Bedrooms'] = condo['Bedrooms'].astype('category')

Extract Year, Month_Year, and Month from Conctract date

In [ ]:
# prompt: how to extract Year from 'Contract_Date' intoa new column called Year

condo['Contract_Date'] = pd.to_datetime(condo['Contract_Date'])
condo['Year'] = condo['Contract_Date'].dt.year

In [ ]:
# prompt: how to extract Month_Year from  'Contract_Date' intoa new column called Month_Year

condo['Month_Year'] = condo['Contract_Date'].dt.strftime('%m-%Y')

In [ ]:
# prompt: how to extract Month from  'Contract_Date' in to a new column called Month

condo['Month'] = condo['Contract_Date'].dt.strftime('%m')

In [ ]:
condo.head(2)

,ML#,Style,Development,Sold_Price,Baths_Full,Baths_Half,Bath,Bedrooms,REO,Appearance,Approx_Int_Square_Footage,Unit_on_Floor_#,Contract_Date,Days_On_Market,Listing_Date,Title_Date,Appearance_Ordinal,REO_Ordinal,Year,Month_Year,Month
1,3289207,Other,Rocky Point Owners,76000,1,0,1,1,N,Excellent,NaN,2.0,2021-04-07,44.0,2/21/2021,7/16/2021,3.0,0,2021.0,04-2021,04
2,3324007,Other,Rocky Point Cooperative,104900,1,0,1,1,N,NaN,NaN,2.0,2021-11-30,160.0,6/23/2021,2/23/2022,0.0,0,2021.0,11-2021,11

In [ ]:
# prompt: change Year into date type

condo['Year'] = condo['Year'].astype('datetime64[ns]')
condo['Month_Year'] = condo['Month_Year'].astype('datetime64[ns]')

In [ ]:
condo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 217 entries, 1 to 254
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ML#                        217 non-null    object
 1   Style                      214 non-null    object
 2   Development                217 non-null    object
 3   Sold_Price                 217 non-null    object
 4   Baths_Full                 217 non-null    int64
 5   Baths_Half                 217 non-null    int64
 6   Bath                       217 non-null    int64
 7   Bedrooms                   217 non-null    category
 8   REO                        217 non-null    object
 9   Appearance                 162 non-null    object
 10  Approx_Int_Square_Footage  70 non-null     object
 11  Unit_on_Floor_#            201 non-null    float64
 12  Contract_Date              216 non-null    datetime64[ns]
 13  Days_On_Market             216 non-null    float64
 14  Listing_Date               217 non-null    object
 15  Title_Date                 214 non-null    object
 16  Appearance_Ordinal         217 non-null    float64
 17  REO_Ordinal                217 non-null    int64
 18  Year                       216 non-null    datetime64[ns]
 19  Month_Year                 216 non-null    datetime64[ns]
 20  Month                      216 non-null    object
dtypes: category(1), datetime64[ns](3), float64(3), int64(4), object(10)
memory usage: 36.0+ KB

Just look at RockyPt

In [ ]:
def replace_artist(text):
    if isinstance(text, str) and 'Rocky' in text:
        return 'Rocky Point'
    else:
        return text

# Apply the custom function to the 'Development' column
condo['Development'] = condo['Development'].apply(replace_artist)

In [ ]:
# prompt: now filter keeping only Developments matching Rocky Point

RockyPt = condo[condo['Development'] == 'Rocky Point']

In [ ]:
# Convert 'Unit_on_Floor_#' to a categorical data type
RockyPt['Unit_on_Floor_#'] = pd.Categorical(RockyPt['Unit_on_Floor_#'])

<ipython-input-22-ca187693972f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RockyPt['Unit_on_Floor_#'] = pd.Categorical(RockyPt['Unit_on_Floor_#'])

In [ ]:
# prompt: drop row 133

RockyPt.drop(index=133, inplace=True)

<ipython-input-23-a5c63670dd49>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RockyPt.drop(index=133, inplace=True)

In [ ]:
# Assuming 'RockyPt' is your DataFrame
RockyPt['Sold_Price'] = pd.to_numeric(RockyPt['Sold_Price'], errors='coerce')

<ipython-input-24-5d5ac4af806c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RockyPt['Sold_Price'] = pd.to_numeric(RockyPt['Sold_Price'], errors='coerce')

In [ ]:
# prompt: how to convert Month_Year to date type

RockyPt['Month_Year'] = pd.to_datetime(RockyPt['Month_Year'], format='%m-%Y')

<ipython-input-25-4c28bc170444>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RockyPt['Month_Year'] = pd.to_datetime(RockyPt['Month_Year'], format='%m-%Y')

In [ ]:
RockyPt['Unit_on_Floor_#'] = pd.Categorical(RockyPt['Unit_on_Floor_#'])

<ipython-input-26-2f3e39183b89>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RockyPt['Unit_on_Floor_#'] = pd.Categorical(RockyPt['Unit_on_Floor_#'])

In [ ]:
RockyPt2 = RockyPt[RockyPt['Unit_on_Floor_#'] == '2.0']

In [ ]:
# prompt: convert Unit on floor # NaN to 1

RockyPt['Unit_on_Floor_#'].fillna(1, inplace=True)

<ipython-input-28-e82afa17b355>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RockyPt['Unit_on_Floor_#'].fillna(1, inplace=True)

# Plot RockyPT Sales

In [ ]:
# RockyPt2['Appearance_Ordinal'] = RockyPt2['Appearance_Ordinal'].astype('category')
# RockyPt
RockyPt['Unit_on_Floor_#'] = RockyPt['Unit_on_Floor_#'].astype('category')

In [ ]:
# Create the scatter plot with increased point size
fig = px.scatter(data_frame=RockyPt, x='Month_Year', y='Sold_Price', color='Unit_on_Floor_#',
                 title='Rocky Pt 2nd Floor Units Colored by Condition',
                 labels={'Development': 'Development', 'Sold_Price': 'Sold Price', 'Town': 'Town'},
                 hover_data=['Development'])

# Show the legend
fig.update_traces(showlegend=True)

# Update the x-axis labels to be rotated 45 degrees
fig.update_xaxes(tickangle=45)

# Update other layout settings as needed
fig.update_layout(template='plotly_white')
fig.update_layout(width=1000)
fig.update_layout(height=600)
fig.update_layout(plot_bgcolor='lightblue')

# Use 'tickformat' to display month and year
fig.update_xaxes(type='date', tickformat='%b-%Y', dtick='M1')  # Set dtick to 'M1' to show tick marks each month

fig.update_traces(marker_size=10)

fig.show()

In [ ]:
# # Sort the DataFrame by 'Month_Year' in ascending order
# RockyPt = RockyPt.sort_values(by='Month_Year')

# # Create the scatter plot
# fig = px.scatter(data_frame=RockyPt, x='Month_Year', y='Sold_Price', color='Unit_on_Floor_#',
#                  title='Rocky Pt Sold Price vs. Floor',
#                  labels={'Development': 'Development', 'Sold_Price': 'Sold Price', 'Town': 'Town'},
#                  hover_data=['Development'])

# # Show the legend
# fig.update_traces(showlegend=True)

# # Update the x-axis labels to be rotated 45 degrees
# fig.update_xaxes(tickangle=45)

# # Update other layout settings as needed
# fig.update_layout(template='plotly_white')
# fig.update_layout(width=1000)
# fig.update_layout(height=600)
# fig.update_layout(plot_bgcolor='lightblue')

# # Use 'tickformat' to display month and year
# fig.update_xaxes(type='date', tickformat='%b-%Y', dtick='M1')  # Set dtick to 'M1' to show tick marks each month

# fig.update_traces(marker_size=10)

# fig.show()

# Now lets just look at 2nd and color by condition

In [ ]:
RockyPt.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23 entries, 23 to 31
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ML#                        23 non-null     object
 1   Style                      23 non-null     object
 2   Development                23 non-null     object
 3   Sold_Price                 23 non-null     int64
 4   Baths_Full                 23 non-null     int64
 5   Baths_Half                 23 non-null     int64
 6   Bath                       23 non-null     int64
 7   Bedrooms                   23 non-null     category
 8   REO                        23 non-null     object
 9   Appearance                 15 non-null     object
 10  Approx_Int_Square_Footage  5 non-null      object
 11  Unit_on_Floor_#            23 non-null     float64
 12  Contract_Date              23 non-null     datetime64[ns]
 13  Days_On_Market             23 non-null     float64
 14  Listing_Date               23 non-null     object
 15  Title_Date                 23 non-null     object
 16  Appearance_Ordinal         23 non-null     float64
 17  REO_Ordinal                23 non-null     int64
 18  Year                       23 non-null     datetime64[ns]
 19  Month_Year                 23 non-null     datetime64[ns]
 20  Month                      23 non-null     object
dtypes: category(1), datetime64[ns](3), float64(3), int64(5), object(9)
memory usage: 4.0+ KB

In [ ]:
# prompt: how many of each of Unit_on_Floor_#

RockyPt['Unit_on_Floor_#'].value_counts()

2.0    12
1.0    11
Name: Unit_on_Floor_#, dtype: int64

In [ ]:
# prompt: convert unit on floor number to integer

RockyPt['Unit_on_Floor_#'] = pd.to_numeric(RockyPt['Unit_on_Floor_#'], errors='coerce')

In [ ]:
RockyPt['Unit_on_Floor_#'].unique()

array([1., 2.])

In [ ]:
RockyPt.head(20)

### Struggling to filter for just 2nd floor

In [ ]:
# prompt: Create new DF by filtering Unit_on_Floor_# to just those rows wehre that equals "2."


RockyPt2 = RockyPt[RockyPt['Unit_on_Floor_#'] == 2.0]
RockyPt2

,ML#,Style,Development,Sold_Price,Baths_Full,Baths_Half,Bath,Bedrooms,REO,Appearance,Approx_Int_Square_Footage,Unit_on_Floor_#,Contract_Date,Days_On_Market,Listing_Date,Title_Date,Appearance_Ordinal,REO_Ordinal,Year,Month_Year,Month
1,3289207,Other,Rocky Point,76000,1,0,1,1,N,Excellent,NaN,2.0,2021-04-07,44.0,2/21/2021,7/16/2021,3.0,0,1970-01-01 00:00:00.000002021,2021-04-01,04
178,3293103,Other,Rocky Point,84000,1,0,1,1,N,Excellent,NaN,2.0,2021-04-01,19.0,3/08/2021,7/06/2021,3.0,0,1970-01-01 00:00:00.000002021,2021-04-01,04
4,3337281,Garden Apartment,Rocky Point,130000,1,0,1,1,N,Mint,NaN,2.0,2021-08-31,21.0,8/10/2021,3/01/2022,4.0,0,1970-01-01 00:00:00.000002021,2021-08-01,08
2,3324007,Other,Rocky Point,104900,1,0,1,1,N,NaN,NaN,2.0,2021-11-30,160.0,6/23/2021,2/23/2022,0.0,0,1970-01-01 00:00:00.000002021,2021-11-01,11
25,3353224,Garden Apartment,Rocky Point,127700,1,0,1,1,N,Excellent,NaN,2.0,2021-11-02,17.0,10/16/2021,1/07/2022,3.0,0,1970-01-01 00:00:00.000002021,2021-11-01,11
223,3374377,Garden Apartment,Rocky Point,135000,1,0,1,1,N,NaN,NaN,2.0,2022-03-16,36.0,2/07/2022,6/10/2022,0.0,0,1970-01-01 00:00:00.000002022,2022-03-01,03
134,H6206350,Garden Apartment,Rocky Point,117000,1,0,1,1,N,NaN,800,2.0,2022-09-14,20.0,8/25/2022,12/20/2022,0.0,0,1970-01-01 00:00:00.000002022,2022-09-01,09
139,3441681,Garden Apartment,Rocky Point,140000,1,0,1,1,N,Mint,NaN,2.0,2022-11-21,17.0,11/04/2022,1/20/2023,4.0,0,1970-01-01 00:00:00.000002022,2022-11-01,11
246,3442030,Garden Apartment,Rocky Point,135000,1,0,1,1,N,NaN,NaN,2.0,2022-11-28,20.0,11/07/2022,1/30/2023,0.0,0,1970-01-01 00:00:00.000002022,2022-11-01,11
104,3438863,Garden Apartment,Rocky Point,145000,1,0,1,1,N,Excellent,800,2.0,2022-12-05,34.0,10/22/2022,2/23/2023,3.0,0,1970-01-01 00:00:00.000002022,2022-12-01,12
185,3454244,Garden Apartment,Rocky Point,135000,1,0,1,1,N,Mint ++,NaN,2.0,2023-02-17,24.0,1/24/2023,5/02/2023,0.0,0,1970-01-01 00:00:00.000002023,2023-02-01,02
27,3466844,Garden Apartment,Rocky Point,155000,1,0,1,1,N,Excellent,NaN,2.0,2023-05-04,41.0,3/24/2023,7/20/2023,3.0,0,1970-01-01 00:00:00.000002023,2023-05-01,05

In [ ]:
RockyPt2['Appearance_Ordinal'] = RockyPt2['Appearance_Ordinal'].astype('category')

In [ ]:
# Create the scatter plot with increased point size
fig = px.scatter(data_frame=RockyPt2, x='Month_Year', y='Sold_Price', color='Appearance_Ordinal',
                 title='Rocky Pt 2nd Floor Units Colored by Condition',
                 labels={'Development': 'Development', 'Sold_Price': 'Sold Price', 'Town': 'Town'},
                 hover_data=['Development'])

# Show the legend
fig.update_traces(showlegend=True)

# Update the x-axis labels to be rotated 45 degrees
fig.update_xaxes(tickangle=45)

# Update other layout settings as needed
fig.update_layout(template='plotly_white')
fig.update_layout(width=1000)
fig.update_layout(height=600)
fig.update_layout(plot_bgcolor='lightblue')

# Use 'tickformat' to display month and year
fig.update_xaxes(type='date', tickformat='%b-%Y', dtick='M1')  # Set dtick to 'M1' to show tick marks each month

fig.update_traces(marker_size=10)

fig.show()

In [ ]:
RockyPt3 = RockyPt2

In [ ]:
appearance_data = RockyPt3

def map_existing_values(value):
    if pd.isna(value):  # Handle NaN values explicitly
        return 0
    if value == "Appearance":
        return 0
    elif value in ["AS IS"]:
        return "As Is"
    elif value in ["Fair", "good", "Good", "Very Good", "Very good"]:
        return "Good"
    elif value in ["Excellent", "EXCELLENT"]:
        return "Excellent"
    elif value == "Move in":
        return "Excellant"
    elif value in ["diamond", "Diamond", "Mint", "mint", "Mint+", "Mint++", "Mint+++", "Mint+++"]:
        return "Mint"
    elif value == "unknown":
        return "Unknown"

RockyPt3['Appearance_Ordinal'] = RockyPt3['Appearance'].apply(map_existing_values)

In [ ]:
RockyPt3.head(5)

,ML#,Style,Development,Sold_Price,Baths_Full,Baths_Half,Bath,Bedrooms,REO,Appearance,Approx_Int_Square_Footage,Unit_on_Floor_#,Contract_Date,Days_On_Market,Listing_Date,Title_Date,Appearance_Ordinal,REO_Ordinal,Year,Month_Year,Month
1,3289207,Other,Rocky Point,76000,1,0,1,1,N,Excellent,NaN,2.0,2021-04-07,44.0,2/21/2021,7/16/2021,Excellent,0,1970-01-01 00:00:00.000002021,2021-04-01,04
178,3293103,Other,Rocky Point,84000,1,0,1,1,N,Excellent,NaN,2.0,2021-04-01,19.0,3/08/2021,7/06/2021,Excellent,0,1970-01-01 00:00:00.000002021,2021-04-01,04
4,3337281,Garden Apartment,Rocky Point,130000,1,0,1,1,N,Mint,NaN,2.0,2021-08-31,21.0,8/10/2021,3/01/2022,Mint,0,1970-01-01 00:00:00.000002021,2021-08-01,08
2,3324007,Other,Rocky Point,104900,1,0,1,1,N,NaN,NaN,2.0,2021-11-30,160.0,6/23/2021,2/23/2022,0,0,1970-01-01 00:00:00.000002021,2021-11-01,11
25,3353224,Garden Apartment,Rocky Point,127700,1,0,1,1,N,Excellent,NaN,2.0,2021-11-02,17.0,10/16/2021,1/07/2022,Excellent,0,1970-01-01 00:00:00.000002021,2021-11-01,11

In [ ]:
# Convert the `Appearance_Ordinal` variable to a categorical variable.
RockyPt3['Appearance_Ordinal'] = RockyPt3['Appearance_Ordinal'].astype('category')

In [ ]:
# Create the scatter plot with increased point size
fig = px.scatter(data_frame=RockyPt3, x='Month_Year', y='Sold_Price', color='Appearance_Ordinal',
                 title='Rocky Pt 2nd Floor Units Colored by Condition',
                 labels={'Development': 'Development', 'Sold_Price': 'Sold Price', 'Town': 'Town'},
                 hover_data=['Development'])

# Show the legend
fig.update_traces(showlegend=True)

# Update the x-axis labels to be rotated 45 degrees
fig.update_xaxes(tickangle=45)

# Update other layout settings as needed
fig.update_layout(template='plotly_white')
fig.update_layout(width=1000)
fig.update_layout(height=600)
fig.update_layout(plot_bgcolor='lightblue')

# Use 'tickformat' to display month and year
fig.update_xaxes(type='date', tickformat='%b-%Y', dtick='M1')  # Set dtick to 'M1' to show tick marks each month

fig.update_traces(marker_size=10)

fig.show()

# info

In [ ]:
RockyPt3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12 entries, 1 to 27
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ML#                        12 non-null     object
 1   Style                      12 non-null     object
 2   Development                12 non-null     object
 3   Sold_Price                 12 non-null     int64
 4   Baths_Full                 12 non-null     int64
 5   Baths_Half                 12 non-null     int64
 6   Bath                       12 non-null     int64
 7   Bedrooms                   12 non-null     category
 8   REO                        12 non-null     object
 9   Appearance                 8 non-null      object
 10  Approx_Int_Square_Footage  2 non-null      object
 11  Unit_on_Floor_#            12 non-null     float64
 12  Contract_Date              12 non-null     datetime64[ns]
 13  Days_On_Market             12 non-null     float64
 14  Listing_Date               12 non-null     object
 15  Title_Date                 12 non-null     object
 16  Appearance_Ordinal         11 non-null     object
 17  REO_Ordinal                12 non-null     int64
 18  Year                       12 non-null     datetime64[ns]
 19  Month_Year                 12 non-null     datetime64[ns]
 20  Month                      12 non-null     object
dtypes: category(1), datetime64[ns](3), float64(2), int64(5), object(10)
memory usage: 2.2+ KB

In [ ]:
RockyPt3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12 entries, 1 to 27
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ML#                        12 non-null     object
 1   Style                      12 non-null     object
 2   Development                12 non-null     object
 3   Sold_Price                 12 non-null     int64
 4   Baths_Full                 12 non-null     int64
 5   Baths_Half                 12 non-null     int64
 6   Bath                       12 non-null     int64
 7   Bedrooms                   12 non-null     category
 8   REO                        12 non-null     object
 9   Appearance                 8 non-null      object
 10  Approx_Int_Square_Footage  2 non-null      object
 11  Unit_on_Floor_#            12 non-null     float64
 12  Contract_Date              12 non-null     datetime64[ns]
 13  Days_On_Market             12 non-null     float64
 14  Listing_Date               12 non-null     object
 15  Title_Date                 12 non-null     object
 16  Appearance_Ordinal         11 non-null     category
 17  REO_Ordinal                12 non-null     int64
 18  Year                       12 non-null     datetime64[ns]
 19  Month_Year                 12 non-null     datetime64[ns]
 20  Month                      12 non-null     object
dtypes: category(2), datetime64[ns](3), float64(2), int64(5), object(9)
memory usage: 2.2+ KB

In [ ]:
RockyPt.head(3)

,ML#,Style,Development,Sold_Price,Baths_Full,Baths_Half,Bath,Bedrooms,REO,Appearance,Approx_Int_Square_Footage,Unit_on_Floor_#,Contract_Date,Days_On_Market,Listing_Date,Title_Date,Appearance_Ordinal,REO_Ordinal,Year,Month_Year,Month
23,3281551,Garden Apartment,Rocky Point,85000,1,0,1,1,N,NaN,950,1.0,2021-02-05,18.0,1/18/2021,6/07/2021,0.0,0,1970-01-01 00:00:00.000002021,2021-02-01,02
1,3289207,Other,Rocky Point,76000,1,0,1,1,N,Excellent,NaN,2.0,2021-04-07,44.0,2/21/2021,7/16/2021,3.0,0,1970-01-01 00:00:00.000002021,2021-04-01,04
178,3293103,Other,Rocky Point,84000,1,0,1,1,N,Excellent,NaN,2.0,2021-04-01,19.0,3/08/2021,7/06/2021,3.0,0,1970-01-01 00:00:00.000002021,2021-04-01,04